###object-detection-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
  labels:
    app: object-detection-app
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8081'
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: object-detection-app
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP