###object-detection-edge-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-edge-deployment
  labels:
    app: object-detection-edge-app  # This label must match the service selector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: object-detection-edge-app
  template:
    metadata:
      labels:
        app: object-detection-edge-app
    spec:
      containers:
        - name: object-detection-edge-container
          image: anton0303/object-detection-edge-app:v1
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          env:
            - name: FLASK_ENV
              value: development
            - name: FLASK_DEBUG
              value: "1"
            - name: DEBUG
              value: "False"
---
apiVersion: v1
kind: Service
metadata:
  name: object-detection-edge-service
  labels:
    app: object-detection-edge-app
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8081'
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: object-detection-edge-app
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP