### object-detection-monitored-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
spec:
  selector:
    app: object-detection-app
  ports:
    - protocol: TCP
      port: 8081            # Internal service port
      targetPort: 5000       # Container port inside the pod
  type: ClusterIP           # Internal access only

